name: sparsecca
channels:
  - conda-forge
dependencies:
  - python<=3.9
  - pandas
  - numpy
  - statsmodels
  # developer dependencies
  - rpy2
  - r-base=4
  - r-data.table
  - r-pma
  - pytest
  - pip
  - pip:
    - git+https://github.com/theislab/sparsecca.git
